import { ConfirmDialog } from "@poly/ui";

interface RevertModalProps {
  onClose: () => void;
  onConfirm: () => void;
  isLoading: boolean;
}

export function RevertModal({ onClose, onConfirm, isLoading }: RevertModalProps) {
  return (
    <ConfirmDialog
      open
      onOpenChange={onClose}
      title="Revert to Original"
      description="This will restore the transcript to its original state before any edits. This action cannot be undone."
      content="All your edits will be lost and the transcript will be reverted to the original version generated by the transcription engine."
      confirmText={isLoading ? "Reverting..." : "Revert to Original"}
      onConfirm={onConfirm}
      variant="destructive"
      isLoading={isLoading}
    />
  );
}
