import { AlertTriangle, Loader2 } from "lucide-react";

import { Button } from "@poly-ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@poly-ui/dialog";

interface RevertModalProps {
  onClose: () => void;
  onConfirm: () => void;
  isLoading: boolean;
}

export function RevertModal({ onClose, onConfirm, isLoading }: RevertModalProps) {
  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-destructive">
            <AlertTriangle className="w-5 h-5" />
            Revert to Original
          </DialogTitle>
          <DialogDescription>
            This will restore the transcript to its original state before any edits.
            This action cannot be undone.
          </DialogDescription>
        </DialogHeader>

        <div className="py-4">
          <p className="text-sm text-muted-foreground">
            All your edits will be lost and the transcript will be reverted to the
            original version generated by the transcription engine.
          </p>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={isLoading}>
            Cancel
          </Button>
          <Button
            variant="destructive"
            onClick={onConfirm}
            disabled={isLoading}
          >
            {isLoading ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Reverting...
              </>
            ) : (
              "Revert to Original"
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
