[project]
name = "poly-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "poly-db",
    "fastapi[standard]>=0.127.0",
    "poly-redis",
    "poly-stt",
    "pydantic-settings>=2.12.0",
    "python-multipart>=0.0.21",
    "slowapi>=0.1.9",
    "stripe>=14.1.0",
    "uvicorn[standard]>=0.40.0",
    "sqlalchemy>=2.0.45",
    "poly-core",
]

[tool.uv.sources]
poly-db = { path = "../../packages/storage/poly-db", editable = true }
poly-redis = { path = "../../packages/storage/redis", editable = true }
poly-stt = { path = "../../packages/stt", editable = true }
poly-core = { path = "../../packages/poly-core", editable = true }
